'use strict';var r=function(){function k(){if(!v.contains("scrollBarWidth")){var d=jQuery("<div>").css({visibility:"hidden",width:100,overflow:"scroll"}).appendTo("body"),h=jQuery("<div>").css({width:"100%"}).appendTo(d).outerWidth();d.remove();v.put("scrollBarWidth",100-h)}return v.get("scrollBarWidth")}function p(d,h){function b(a){return a.uid}var a=[],e={},z="function"===typeof h?h:b;d.w?(a=d.items,e=d.w):jQuery.each(d,function(b,c){var n=z(c);n&&!e[n]&&(a.push(c),e[n]=b)});this.items=Object.freeze(a);
this.w=Object.freeze(e);this.get=function(b){return a[e[b]]};this.length=a.length}var e=function(){function d(d,b){try{return b?new CustomEvent(d,{detail:b}):new Event(d)}catch(C){if(b){var a=document.createEvent("CustomEvent");a.initCustomEvent(d,!0,!0,b);return a}b=document.createEvent("Event");b.initEvent(d,!0,!0);return b}}return Object.freeze({GRID_LAYOUT:"GRID_LAYOUT",GRID_FOCUS:"GRID_FOCUS",GRID_CHANGE_CONTENTS:"GRID_CHANGE_CONTENTS",GRID_CHANGE_OPTIONS:"GRID_CHANGE_OPTIONS",GRID_SHOW_TEXTAREA:"GRID_SHOW_TEXTAREA",
GRID_HIDE_TEXTAREA:"GRID_HIDE_TEXTAREA",GRID_SHOW_CURSOR:"GRID_SHOW_CURSOR",GRID_HIDE_CURSOR:"GRID_HIDE_CURSOR",GRID_SHOW_INPUT:"GRID_SHOW_INPUT",GRID_HIDE_INPUT:"GRID_HIDE_INPUT",GRID_SHOW_SELECT:"GRID_SHOW_SELECT",GRID_HIDE_SELECT:"GRID_HIDE_SELECT",GRID_CHANGE_TEXT:"GRID_CHANGE_TEXT",CHANGE_FONT_SIZE:"CHANGE_FONT_SIZE",CHANGE_CONTENT_HEIGHT:"CHANGE_CONTENT_HEIGHT","new":d,dispatch:function(h,b,a){a instanceof jQuery?a=a.get(0):"string"===typeof a&&(a=document.getElementById(a));(a||document).dispatchEvent(d(h,
b))}})}(),m=function(){function d(a,b){a=a instanceof jQuery?a:$(a);var d=h(b);d&&b.body?a.addClass(d).text(b.body).show():a.hide().text("").removeClass("Mes_error Mes_information Mes_warning")}function h(a){if(a)switch(a.type){case "INFORMATION":return"Mes_information";case "WARNING":return"Mes_warning";case "ERROR":return"Mes_error";default:return null}else return null}function b(a,b){this.type=a;this.body=b}return Object.freeze({information:function(a){return new b("INFORMATION",a)},warning:function(a){return new b("WARNING",
a)},error:function(a){return new b("ERROR",a)},show:d,hide:function(a){d(a,null)}})}(),v=function(){function d(c){if("string"===typeof c)return"c4th_"+c}function h(c,a){"function"===typeof a?h(c,a()):"string"===typeof c&&sessionStorage.setItem(d(c),JSON.stringify(e(a)))}function b(c,a,l){if("function"===typeof a)b(c,a(),l);else if("string"===typeof c){c=d(c);var n=JSON.parse(sessionStorage.getItem(c));n?(l.pre&&(n=n.filter(l.pre)),l.validate&&!l.validate(a)||n.push(a)):n=[a];sessionStorage.setItem(c,
JSON.stringify(n))}}function a(c){if(c instanceof RegExp)for(var a=0;a<sessionStorage.length;)c.test(sessionStorage.key(a).substring(5))?sessionStorage.removeItem(sessionStorage.key(a)):++a;else for(a=0;a<sessionStorage.length;)c===sessionStorage.key(a).substring(5)?sessionStorage.removeItem(sessionStorage.key(a)):++a}function e(a){return"string"===typeof a?Object.freeze(new m(a)):a instanceof p?Object.freeze(new c(a)):a}function k(c){if(c)switch(c.B){case "plain_text":return c.value;case "ordered_map":return new p(c.value);
default:return c}else return c}function m(c){this.B="plain_text";this.value=c}function c(c){this.B="ordered_map";this.value=c}return Object.freeze({toKey:d,contains:function(c){c=d(c);for(var a=0;a<sessionStorage.length;a++)if(c===sessionStorage.key(a))return!0;return!1},get:function(c){try{return k(JSON.parse(sessionStorage.getItem(d(c))))}catch(D){a(c)}},put:h,push:b,remove:a})}(),x=function(){function d(){var b=[];h(b,v.get("c4thMenu").tabs,[function(a){return a.buttons},function(a){return a.categories},
function(a){return a.items}]);jQuery("#menu").html(b.join(""));console.log("done")}function h(b,a,d){b.push("<ul>");a.forEach(function(a){b.push("<li>");a.roman?(b.push('<span data-narrow="'),b.push(a.label),b.push(" "),b.push(a.roman),b.push('">')):b.push("<span>");b.push(a.label);b.push("</span>");0<d.length&&h(b,d[0](a),d.slice(1));b.push("</li>")});b.push("</ul>")}return Object.freeze({load:function(){console.log("start");jQuery.getJSON("rest/menus.json",function(b){v.put("c4thMenu",b.menus)})},
reload:function(b){b.key===v.I("c4thMenu")&&b.newValue&&d()},build:d,narrow:function(b){jQuery("#menu span").removeClass("match hidden");b&&(b=jQuery('#menu span[data-narrow *= "'+b+'"]'),b.addClass("match"),b.parentsUntil("#menu > ul > li > ul","li").children("span").addClass("match"))}})}(),w=function(){function d(d,b,a,e){var h=window.contextPath+"/rest/";return jQuery.ajax({url:b.substr(0,h.length)!==h?h+b:b,type:d,dataType:e||"json",contentType:"application/json; charset=utf-8",data:"GET"===
d?jQuery.extend({},a,{c4thSessionId:window.c4thSessionId}):JSON.stringify(a)})}return Object.freeze({get:function(e,b,a){return d("GET",e,b,a)},post:function(e,b,a){return d("POST",e,b,a)},put:function(e,b,a){return d("PUT",e,b,a)},"delete":function(e,b,a){return d("DELETE",e,b,a)}})}(),A=function(){function d(c,a,b){this.target=c;this.H=a;this.props=b;c=this.getData();this.props.a=c.f.fixedColumns;this.props.m=0<c.f.fixedColumns;c=this.G(c);this.C(c.elements);this.l=c.l;this.j=c.j}function h(c){c=
c.querySelectorAll("[data-horTabIndex]");for(var a=0,b;b=c[a];++a)b.tabIndex=b.attributes["data-horTabIndex"].value}function b(c,b,d,e,h){var l=function(){for(var a=[],f=0,b;b=(c||[])[f];++f)a[f]=b;return Object.freeze(a)}(),n=function(){var g=[];if(c)for(var f=0;f<d;++f)g[f]=new a(c,b[f],f,e,h);else for(f=0;f<d;++f)g.push([]);return Object.freeze(g)}();this.rows=l;this.b=n;this.v=!(0<(n[0].rows||[]).length);this.g=function(c,a){if(this.v)a&&(c[2].innerHTML="<div class='g_EmptySetMsg'>".concat(a,
"</div>"));else{a=[];for(var f=[],u=0,q;q=n[u];++u){var d="<div class='g_N g_N".concat(u);b[u]&&b[u].styleClass&&(d=d.concat(" ",b[u].styleClass.join(" ")));d=d.concat("'>");u<h.a?(a.push(d.concat(q.g(),"</div>")),f.push(d+"</div>")):f.push(d.concat(q.g(),"</div>"))}c[2].innerHTML=f.join("");c[1].innerHTML=a.join("")}}}function a(c,a,b,d,e){var n=function(){for(var a=[],g=0,f;f=c[g];++g)a[g]=new m(f.item,g,b,d,e);return Object.freeze(a)}();this.f=Object.freeze(a);this.rows=n;this.g=function(){var c=
d?p(a):{};return n.map(function(a){return a.g(c)}).join("")}}function m(c,a,b,d,e){function n(a){return(a||[]).map(function(a){return" "+a.key+"='"+a.value+"'"}).join("")}function l(a,c,b,u,d,e){function f(c){var b=["<option value='",c.value,"'"];c.value===a.uid&&b.push(" selected='selected'");b.push(">",c.text,"</option>");return b.join("")}function q(){return[" data-horTabIndex='",c*b+u,"' data-verTabIndex='",c+u*d,"'"].join("")}var g="";"area"===e.text?g=["<textarea",q()," class='invisible'>",
a.text,"</textarea>"].join(""):"numeric"===e.text?g=["<input type='text'",q()," value='",a.text,"' class='invisible' />"].join(""):e.options&&(g=["<select",q()," class='invisible'>",e.options.map(f).join(""),"</select>"].join(""));return["<span>",a.text||"&nbsp;","</span>"].join("")+g}Object.freeze(c[b]);this.g=function(g){var f=["<div class='g_W",a," g_L'"];d&&b>=e.a&&f.push(" data-rowindex='",a,"' data-colindex='",b-e.a,"'");f.push(n(c[b].attr),c[b].modified?" data-modded=true":"",">");f.push(l(c[b],
a,e.rows,b,e.b,g));f.push("</div>");return f.join("")}}function p(a){var c={};(a.attr||[]).forEach(function(a){c[a.key]=a.value||v(a)});return c}function v(a){var c=[];(a.attr||[]).forEach(function(a){c.push(p(a))});return c}d.prototype.getData=function(){return function(a,d){var c=a?(a.column?a.column:(a.head||a.body)[0].item).length:0,e=Object.freeze(a.column?a.column:[]);a=Object.freeze({head:new b(a.head,e,c,!1,d),body:new b(a.body,e,c,!0,d),f:a.metadata});d.b=c;d.rows=(a.body.b[0].rows||[]).length;
d.h=!a.head.v;Object.seal(d);return a}(function(a){switch(typeof a){case "string":return window.JSON.parse(a);case "object":return a;default:return null}}(this.H),this.props)};d.prototype.G=function(a){function c(a){if(a.target.classList.contains("selectable")){for(var c=f.body[2].querySelectorAll(".selected"),b=0,d;d=c[b];++b)d!=a.target&&d.classList.remove("selected");a.target.classList.add("selected")}}function b(a,c,b,d){a&&a.preventDefault();a=parseInt(c.attributes["data-rowindex"].value,10);
c=parseInt(c.attributes["data-colindex"].value,10);for(var f=t.props.rows-1,u=t.props.b-t.props.a-1,q=a+b,g=c+d;;){if(0>g)if(0<q)g=u,--q;else break;else if(g>u)if(q<f)g=0,++q;else break;else if(0>q)if(0<g)--g,q=f;else break;else if(q>f)if(g<u)++g,q=0;else break;if(q==a&&g==c||e(q,g))break;else q+=b,g+=d}}function d(a,c){var b=Math.max(a.offsetTop+a.offsetHeight-f.body[0].offsetHeight+t.props.A,Math.min(f.body[0].scrollTop,a.offsetTop-f.head[0].offsetHeight));a=Math.max(a.offsetLeft+a.offsetWidth-
f.body[0].offsetWidth+t.props.A,Math.min(f.body[0].scrollLeft,a.offsetLeft-f.body[1].offsetWidth));!c&&window.jQuery?$(f.body[0]).finish().animate({scrollTop:b,scrollLeft:a},300):(f.body[0].scrollTop=b,f.body[0].scrollLeft=a)}function e(a,c){var b=f.body[2].querySelector(".selectable[data-rowindex='".concat(a,"'][data-colindex='",c,"']"));if(b){for(var q=f.body[2].querySelectorAll(".selected"),u=0;u<q.length;++u)q[u].classList.remove("selected");b.classList.add("selected");h(b,a,c);d(b,!1);return!0}return!1}
function h(c,b,d){var f=jQuery.extend({},a.body.rows[b]);delete f.item;r.event.dispatch(r.event.GRID_FOCUS,{dom:c,cell:a.body.rows[b].item[d+t.props.a],row:Object.freeze(f),column:a.body.b[d+t.props.a].f,rowIndex:b,colIndex:d},t.target)}function k(a){for(var c=[],b=0;b<arguments.length;++b)c.push(g(arguments[b]));return Object.freeze(c)}function g(a){var c=document.createElement("div");c.className="g_"+a;return c}var f=Object.freeze({c:Object.freeze([document.createDocumentFragment(),g("A")]),head:k("D",
"X","V"),body:k("Y","X","V")}),t=this;f.c[0].appendChild(f.c[1]);f.c[1].appendChild(f.head[0]);f.c[1].appendChild(f.body[0]);f.head[0].appendChild(f.head[1]);f.head[0].appendChild(f.head[2]);f.body[0].appendChild(f.body[1]);f.body[0].appendChild(f.body[2]);a.head.g(f.head);a.body.g(f.body,"No results returned.");t.props.selectable&&f.body[2].addEventListener("click",c);f.body[2].addEventListener("click",function(a){a.target.attributes["data-rowindex"]&&h(a.target,parseInt(a.target.attributes["data-rowindex"].value,
10),parseInt(a.target.attributes["data-colindex"].value,10))});f.body[2].addEventListener("focus",function(a){switch(a.target.tagName.toLowerCase()){case "select":case "textarea":return a.preventDefault(),d(a.target.parentNode,!0),!1}},!0);f.body[2].addEventListener("change",function(c){for(var b=c.target;b;)if(b.attributes["data-rowindex"]){var d,f;switch(c.target.nodeName.toLowerCase()){case "select":d=r.event.GRID_CHANGE_OPTIONS;f=c.target.options[c.target.selectedIndex].textContent;break;case "input":case "textarea":d=
r.event.GRID_CHANGE_TEXT,f=c.target.value}if(d){c=c.target;var g=parseInt(b.attributes["data-rowindex"].value,10),b=parseInt(b.attributes["data-colindex"].value,10);"span"===c.previousElementSibling.tagName.toLowerCase()&&(c.previousElementSibling.textContent=f);var e=jQuery.extend({},a.body.rows[g]);delete e.item;r.event.dispatch(d,{value:c.value,text:f,cell:a.body.rows[g].item[b+t.props.a],row:Object.freeze(e),column:a.body.b[b+t.props.a].f,columnAttributes:p(a.body.b[b+t.props.a].f),rowIndex:g,
colIndex:b},t.target)}break}else b=b.parentNode});t.target.addEventListener(r.event.GRID_SHOW_CURSOR,function(){for(var a=f.body[2].querySelectorAll(".selected"),c=0;c<a.length;++c)a[c].classList.remove("selected");var b=0==a.length?0:a[0].attributes["data-rowindex"].value,a=0==a.length?0:a[0].attributes["data-colindex"].value,d=f.body[2].querySelectorAll('.selectable[data-rowindex="'.concat(b,'"]'));if(0==d.length)f.c[1].classList.remove("selectionsEnabled");else{for(var g=parseInt(d[0].attributes["data-colindex"].value,
10),c=0;c<d.length;++c){var l=parseInt(d[c].attributes["data-colindex"].value,10);if(!(l<a)){g=l;break}}e(b,g);f.c[1].classList.add("selectionsEnabled")}});t.target.addEventListener(r.event.GRID_HIDE_CURSOR,function(){f.c[1].classList.remove("selectionsEnabled")});document.addEventListener("keydown",function(a){var c=f.body[2].querySelector(".selected");if(c)switch(a.keyCode){case 69:case 73:case 38:return b(a,c,-1,0);case 68:case 75:case 40:return b(a,c,1,0);case 83:case 74:case 37:return b(a,c,
0,-1);case 70:case 76:case 39:return b(a,c,0,1)}});return Object.freeze({elements:f,l:function(c,b){var d=f.body[2].querySelector("div[data-rowindex='".concat(c,"'][data-colindex='",b,"']"));if(d){var g=jQuery.extend({},a.body.rows[c]);delete g.item;return Object.freeze({dom:d,cell:a.body.rows[c].item[b+t.props.a],row:Object.freeze(g),column:a.body.b[b+t.props.a].f})}},j:function(c,b){var d,g,e;for(e=0;e<a.body.rows.length;++e)if(a.body.rows[e].uid===c){d=a.body.rows[e];break}for(c=t.props.a;c<a.body.b.length;++c)if(a.body.b[c].f.uid===
b){g=a.body.b[c].f;break}if(d&&g&&(b=f.body[2].querySelector("div[data-rowindex='".concat(e,"'][data-colindex='",c-t.props.a,"']"))))return e=jQuery.extend({},d),delete e.item,Object.freeze({dom:b,cell:d.item[c],row:Object.freeze(e),column:g})}})};d.prototype.C=function(a){function c(){g.target.removeAttribute("style");var c=g.target.id+"SS",d=document.getElementById(c);d&&d.parentNode.removeChild(d);document.head.appendChild(b(g.target.id,c));c=getComputedStyle(g.target);g.props.s=a.c[1].offsetHeight+
parseFloat(c.paddingTop)+5;g.props.u=(document.getElementById("mainContentsWrap")||g.target).offsetTop;g.props.i=parseFloat(c.paddingBottom)+parseFloat(c.borderBottomWidth)+10;g.props.o=a.head[0].offsetHeight+30;p()}function b(c,b){function d(a,c,b){for(var d=0;d<g.props.b;++d)for(var e=((d<g.props.a?c:a)[b][d]||dummyNode).children,l=0,h;h=e[l];++l)if(h.getAttribute("data-rowspan")){h.classList.add("g_WN");for(var k=parseInt(h.getAttribute("data-rowspan"),10),k=Math.min(e.length,l+k)-1,n=0,m=l;m<=
k;++m)n+=e[m].offsetHeight;f["N"+d+" .g_WN.g_W"+l]={height:n+"px"};for(++l;l<=k&&(h=e[l]);++l)h.classList.add("g_WO");--l}}var f={L:{visibility:"visible"},D:{display:"none"},"Y .g_X":{display:"none"}},e=[a.head[2].children,a.body[2].children],l=[a.head[1].children,a.body[1].children];(function(){var c=(g.props.h?a.head[0].offsetHeight:0)+"px",b=a.body[0].offsetWidth-a.body[0].clientWidth+"px",d=a.body[0].offsetHeight-a.body[0].clientHeight+"px";f["Y .g_V"]={padding:c+" 0px 0px 0px"};g.props.h&&(f.D=
{right:b});g.props.m&&(f["Y .g_X"]={top:c,bottom:d})})();(function(a,c){for(var b=0,d=g.props.b;b<d;++b){var e=b<g.props.a?c:a;f["N"+b]={width:Math.max((e[0][b]||dummyNode).offsetWidth,(e[1][b]||dummyNode).offsetWidth)+"px"}}})(e,l);(function(a,c){for(var b=0;b<g.props.rows;++b){for(var d=0,e=0,l=g.props.b;e<l;++e)var h=((e<g.props.a?c:a)[1][e]||dummyNode).children[b]||dummyNode,d=Math.max(d,h&&h!==g.F?h.offsetHeight:0);f["Y .g_W"+b]={height:d+"px"}}})(e,l);d(e,l,0);d(e,l,1);return function(a,c){var b=
[];a="#".concat(a," .g_");for(var d in f){var e=f[d];if(e){b.push(a,d," { ");for(var g in e)b.push(g,":",e[g],"; ");b.push("} ")}}d=document.createElement("style");d.id=c;d.type="text/css";d.appendChild(document.createTextNode(b.join("")));return Object.freeze(d)}(c,b)}function d(){a.head[2].style.marginLeft=-a.body[0].scrollLeft+"px"}function k(){a.body[1].style.marginTop=-a.body[0].scrollTop+"px"}function p(){var a=window.innerHeight-g.props.u-g.props.i;g.target.style.height=(a<g.props.o?window.innerHeight-
g.props.i:Math.min(g.props.s,a))+"px";e.dispatch(e.CHANGE_CONTENT_HEIGHT)}function m(a,b){$("#"+g.target.id+" .g_L "+a).toggle(b).prev("span").toggle(!b).parents(".g_L").toggleClass("selectable",!b);c()}var g=this;g.target.appendChild(a.c[0]);g.props.h&&a.body[0].addEventListener("scroll",d);g.props.m&&a.body[0].addEventListener("scroll",k);window.addEventListener("resize",p);document.addEventListener(e.GRID_LAYOUT,c);g.target.addEventListener(e.GRID_CHANGE_CONTENTS,c);g.target.addEventListener(e.GRID_SHOW_TEXTAREA,
function(){m("textarea",!0)});g.target.addEventListener(e.GRID_HIDE_TEXTAREA,function(){m("textarea",!1)});g.target.addEventListener(e.GRID_SHOW_INPUT,function(){m("input",!0)});g.target.addEventListener(e.GRID_HIDE_INPUT,function(){m("input",!1)});g.target.addEventListener(e.GRID_SHOW_SELECT,function(){m("select",!0)});g.target.addEventListener(e.GRID_HIDE_SELECT,function(){m("select",!1)});c();h(g.target)};d.prototype.F=Object.freeze(new function(){this.children=[];this.offsetWidth=0});return Object.freeze({create:function(a,
b){if(a=a instanceof jQuery?a.get(0):"string"===typeof a?document.getElementById(a):a)return b=new d(Object.freeze(a),b,{b:0,rows:0,a:0,h:!1,m:!1,s:0,u:0,i:0,o:0,A:k()}),Object.freeze({getCell:b.l,findCell:b.j})}})}(),B=function(){function d(a){a=a instanceof jQuery?a:$(a);0<a.length&&(a.removeClass("active"),$(".menuCover").hide(),$(document.body).off("click",b),a.next(".pulldownRow").stop(!0,!0).slideUp(),a.parent().is("#contextMenu")&&$("#toolbars").off("click",e))}function e(){d($(".pulldownHead.active"))}
function b(a){a=$(a.target);a=a.is(".pulldownHead")?a:a.parents(".pulldownRow").prev();d($(".pulldownHead.active").not(a))}return Object.freeze({activate:function(a){var d=a instanceof jQuery?a:$(a);d.addClass("active");d.hasClass("exclusive")&&($(".menuCover").show(),$(document.body).on("click",b));d.next(".pulldownRow").stop(!0,!0).slideDown(function(){if(d.parent().is("#contextMenu"))$("#toolbars").on("click",e)})},deactivate:d,deactivateAll:e})}(),y=function(){return Object.freeze({select:function(d){d=
d&&d.detail&&d.detail.size||d;var h;switch(d){case "large":h="0.8em";break;case "small":h="0.55em";break;default:d="standard",h="0.7em"}localStorage.setItem("fsname",d);jQuery("#fontChanger span[data-value="+d+"]").addClass("active");jQuery("#contentStyles").text(".fontChangeArea { font-size: "+h+"; }");e.dispatch(e.GRID_LAYOUT)}})}();document.addEventListener(e.CHANGE_FONT_SIZE,y.select);return Object.freeze({event:e,message:m,storage:v,menu:x,ajax:w,grid:A,pulldown:B,style:y,OrderedMap:p,topPageSwipe:function(d,
e,b,a){function h(a){a=a||window.event;m=!0;c=a.pageX;n=a.pageY;p=(new Date).getTime()}function k(d){m=!1;if(2E3>=(new Date).getTime()-p){var e=d.pageX-c;d=d.pageY-n;var l=null;50<=Math.abs(e)&&100>=Math.abs(d)&&(l=0>e?1:-1);if(l){a(l);return}}b()}var m=!1,c,n,p;d.on({M:function(a){h(a.changedTouches[0]);m&&a.preventDefault()},K:function(a){m&&(e(a.changedTouches[0].pageX-c),a.preventDefault())},J:function(a){m&&(k(a.changedTouches[0]),a.preventDefault())},mousedown:function(a){h(a);m&&a.preventDefault()},
mousemove:function(a){m&&(e(a.pageX-c),a.preventDefault())},mouseup:function(a){m&&(k(a),a.preventDefault())}});b()},getScrollBarWidth:k})}();
jQuery(function(k){window.c4thSessionId||(k("#sessionTimedout").show(),r.storage.remove(/.*/));(function(){var p=k("#el-loading-pane"),e=[];k(document).ajaxSend(function(){e.push(window.setTimeout(function(){p.show()},500))});k(document).ajaxComplete(function(){window.clearTimeout(e.pop());0===e.length&&p.hide()})})();(function(){k("#fontChanger span").on("click",function(k){r.event.dispatch(r.event.CHANGE_FONT_SIZE,{size:k.currentTarget.attributes["data-value"].value})});r.style.select(localStorage.getItem("fsname"))})();
(function(){var p=k("#headerWrap"),e=k("#toolbars"),m=k("div.hidetab"),v=k("#menuArea"),x=k("#ribbonArea"),w=m.width();m.click(function(){0<k(".pulldownHead.active").length||(1==e.data("hidden")?(e.css("width","100%"),e.css("right","auto"),v.show(),x.show(),e.data("hidden",!1).children().css("left",document.body.offsetWidth-w).animate({left:"0"},"slow",function(){e.css("overflow","visible")}),p.animate({"padding-bottom":"5.6em"},"slow",function(){r.event.dispatch(r.event.GRID_LAYOUT)})):(e.css("overflow",
"hidden"),e.data("hidden",!0).children().animate({left:document.body.offsetWidth-w},"slow",function(){e.css("width",w);e.css("right",0);v.hide();x.hide();m.css("left",0)}),p.animate({"padding-bottom":"1px"},"slow",function(){r.event.dispatch(r.event.GRID_LAYOUT)})))})})();(function(){var p=k(".pulldownHead"),e=k(".menuCover");k("#toolbars");e.on("click",r.pulldown.deactivateAll);p.click(function(){var e=k(this);e.hasClass("active")?r.pulldown.deactivate(e):p.is(".active")||r.pulldown.activate(e)});
k("#pulldownMenu .pulldownRow").on("click",function(e){e=k(e.target);e.is("span")&&r.pulldown.deactivate(e.closest(".pulldownRow").prev(".pulldownHead"))})})()});window.c4th=r;
